version: 2
updates:
- package-ecosystem: npm
  versioning-strategy: increase
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "19:00"
  groups:
    storybook:
      patterns:
        - "@storybook/*"
        - storybook
        - "@chromatic-com/storybook"
        - "@whitespace/storybook-addon-html"
        - "chromatic"
    eslint_esbuild:
      patterns:
        - "eslint*"
        - "@stylistic/eslint-plugin-js"
        - "esbuild-plugin-eslint"
        - "@eslint*"
        - "esbuild*"

    stylelint:
      patterns:
        - "stylelint*"
    vitest:
      patterns:
        - "*vitest*"
  open-pull-requests-limit: 10
  reviewers:
  - qld-gov-au/qld-online-dev-team
