name: Clear Cache Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  clear-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Cache
        run: |
          rm -rf ${{ runner.workspace }}/path/to/cache
        shell: bash
