name: PR Build and Release package

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'master'

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DIGITAL_QHEALTH_WORKFLOW }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"

      - name: Bump version
        run: |
          # Get the label names from the pull request event
          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          # Convert the labels into an array
          IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"

          # Initialize variable to store the highest label
          HIGHEST_LABEL=""

          # Loop through the labels and check for "major, minor, patch"
          for LABEL in "${LABEL_ARRAY[@]}"; do
            if [ "$LABEL" == "major" ] || [ "$LABEL" == "minor" ] || [ "$LABEL" == "patch" ]; then
              HIGHEST_LABEL="$LABEL"
            fi
          done

          # Check if a valid label was found
          if [ -n "$HIGHEST_LABEL" ]; then
            npm version "$HIGHEST_LABEL"
          else
            echo "No version bump label found, skipping release"
            exit 0
          fi

      - name: npm install and build webpack
        run: |
          npm ci
          npm run build

      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ runner.command }} -c "node -p \"require('./package.json').version\""
          operation: release

      - name: Commit and push changes
        run: |
          git add "package.json" "CHANGELOG.md"
          git commit -m "chore: release $(node -p "require('./package.json').version")"
          git push origin HEAD:master

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

      - name: Get version changelog
        id: get-changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ runner.command }} -c "node -p \"require('./package.json').version\""
          operation: read

      - name: Update GitHub release documentation
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ runner.command }} -c "node -p \"require('./package.json').version\""
          body: ${{ steps.get-changelog.outputs.changelog }}
        env:
          token: ${{ secrets.DIGITAL_QHEALTH_WORKFLOW }}
